version: "3.7"

services:
  backend: 
    image: node:latest
    working_dir: /app
    volumes: 
      - .:/app
    command: sh -c 'cd /app && npm run start:dev'
    ports: 
      - 3000:3000
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    expose: 
      - 3306
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:

    