version: "3.7"

services:
  backend: 
    image: node:latest
    working_dir: /app
    volumes: 
      - .:/app
    command: sh -c 'cd /app && npm run start:dev'
    ports: 
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: parallel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    